import type { CSSProperties } from 'react';

const font = '"Nunito Sans", system-ui, sans-serif';

export const colors = {
  textPrimary: '#202027',
  textBody: '#212529',
  textSecondary: '#606068',
  border: '#dfdfe8',
  borderDark: '#bcbcc5',
  surfaceDark: '#202027',
  surfaceMenuBorder: '#37373d',
  placeholder: '#eaeaea',
  hero: '#d9d9d9',
  tagOverlay: 'rgba(32,32,39,0.7)',
  pillActive: '#eaeaea',
  rateTagBg: '#eeeeee',
  /** Checkout northstar `1:5705` */
  tealBrand: '#13948f',
  tealBorder: '#139490',
  /** Rooms & Rates filter pill — Figma `18:7673` */
  filterTealDark: '#116762',
  faqBorder: '#eaeaee',
  surfaceTertiaryTeal: '#edf4f4',
  promoBanner: '#13948f',
  detailsButtonBg: '#f4f4fe',
  reserveOrange: '#f3ab1f',
  textSuccess: '#218921',
  urgencyRed: '#bb1017',
  rateTagTealBg: '#e1f2f2',
  rateTagTealText: '#07211e',
  topPickPurple: '#6a0b96',
  topPickPurpleBorder: '#b485cb',
} as const;

export const textStyles = {
  pageTitle: {
    fontFamily: font,
    fontSize: 20,
    fontWeight: 700,
    lineHeight: '28px',
    color: colors.textPrimary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  sectionTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 18,
    lineHeight: '32px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  labelBold: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 16,
    lineHeight: '22.4px',
    color: colors.textBody,
    margin: 0,
  } satisfies CSSProperties,
  bodyTight: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '22.4px',
    color: colors.textBody,
    margin: 0,
  } satisfies CSSProperties,
  link: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    color: colors.textBody,
    textDecoration: 'underline',
    margin: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    textAlign: 'left',
    alignSelf: 'flex-start',
    width: 'fit-content',
  } satisfies CSSProperties,
  /** Trip summary — Figma `610:22085` */
  tripSummaryLabel: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 16,
    lineHeight: '22.4px',
    color: colors.textBody,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Trip summary date / occupancy — Figma `610:22084`, `610:22083` */
  tripSummaryLine: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '22.4px',
    color: colors.textBody,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** "Change dates" — Figma `610:22081` */
  tripSummaryLink: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '24px',
    color: colors.textBody,
    textDecoration: 'underline',
    textDecorationStyle: 'solid',
    margin: 0,
    marginTop: 4,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    textAlign: 'left',
    alignSelf: 'flex-start',
    width: 'fit-content',
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  roomTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 20,
    lineHeight: '24px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Property header — Figma `616:30738` */
  hotelInfoName: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 20,
    lineHeight: 'normal',
    color: colors.textPrimary,
    margin: 0,
    width: '100%',
  } satisfies CSSProperties,
  /** Property address / phone — Figma `616:30740`, `616:30742` */
  hotelInfoMeta: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '20px',
    color: colors.textSecondary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  captionMedium: {
    fontFamily: font,
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  captionBold: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Northstar `1:5854` — Fully Refundable (green) */
  refundableTitleGreen: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textSuccess,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  refundableDeadlineGreen: {
    fontFamily: font,
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textSuccess,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Recommended subtitle — northstar `1:5828` */
  recommendedSubtitle: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
    width: '100%',
  } satisfies CSSProperties,
  /** “Change dates” — northstar `1:5819` (link size) */
  tripSummaryLinkNorthstar: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textBody,
    textDecoration: 'underline',
    textDecorationStyle: 'solid',
    margin: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Lowest rate pill — northstar `1:5900` */
  lowestRateNorthstar: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '12px',
    color: colors.rateTagTealText,
    margin: 0,
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Filter pill selected — northstar `1:744` */
  filterPillSelected: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.tealBorder,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Featured card — Figma `614:30551` Cancellation title row */
  cancellationTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Featured card — Figma `614:30551` deadline + info icon row */
  cancellationDeadline: {
    fontFamily: font,
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  amenity: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  detailSemi: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '20px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  pill: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  btnSm: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  priceLg: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 12,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  perNight: {
    fontFamily: font,
    fontWeight: 300,
    fontSize: 10,
    lineHeight: '14px',
    color: colors.textSecondary,
    margin: 0,
  } satisfies CSSProperties,
  totalLabel: {
    fontFamily: font,
    fontWeight: 300,
    fontSize: 12,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  totalValue: {
    fontFamily: font,
    fontWeight: 300,
    fontSize: 16,
    lineHeight: '20px',
    color: colors.textPrimary,
  } satisfies CSSProperties,
  taxes: {
    fontFamily: font,
    fontWeight: 300,
    fontSize: 12,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
    textAlign: 'right',
  } satisfies CSSProperties,
  reserve: {
    fontFamily: font,
    fontWeight: 800,
    fontSize: 14,
    lineHeight: '18px',
    color: '#ffffff',
    textTransform: 'uppercase',
    margin: 0,
  } satisfies CSSProperties,
  merchTag: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: '#ffffff',
    margin: 0,
  } satisfies CSSProperties,
  imageCount: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 12,
    color: '#ffffff',
    margin: 0,
  } satisfies CSSProperties,
  lowestRate: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '12px',
    color: colors.textPrimary,
    textTransform: 'uppercase',
    margin: 0,
  } satisfies CSSProperties,
  urgency: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Checkout stepper label (active) — Figma `614:29570`, `614:29576` */
  checkoutStepLabel: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Checkout stepper label (upcoming) — Figma `614:29581` */
  checkoutStepLabelMuted: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '18px',
    color: colors.textSecondary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Review Stay — northstar `1:3140` */
  reviewHotelTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 20,
    lineHeight: 'normal',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  reviewRoomTitle: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '28px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  reviewRoomMeta: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: 'normal',
    color: colors.textSecondary,
    margin: 0,
  } satisfies CSSProperties,
  /** Check-in / check-out labels — northstar `1:3143` / `1:3146` */
  reviewCheckLabel: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textSecondary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Dates under labels — northstar `1:3144` / `1:3147` (14 / 16, primary) */
  reviewCheckDate: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  reviewPolicyTitle: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '16px',
    color: colors.textPrimary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  reviewPolicyBody: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '16px',
    color: colors.textSecondary,
    margin: 0,
  } satisfies CSSProperties,
  reviewCharges: {
    fontFamily: font,
    fontWeight: 500,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  reviewLink: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textSecondary,
    textDecoration: 'underline',
    textDecorationStyle: 'solid',
    margin: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  reviewNext: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '22px',
    color: '#ffffff',
    margin: 0,
  } satisfies CSSProperties,
  /** Review Stay fixed Next — northstar `1:3162` / `_actionBase` */
  reviewStayNext: {
    fontFamily: font,
    fontWeight: 800,
    fontSize: 14,
    lineHeight: '18px',
    color: '#ffffff',
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Enter Details — Figma `614:29680`, `614:29691` */
  detailsSectionTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 20,
    lineHeight: '22px',
    color: colors.textPrimary,
    margin: 0,
    width: '100%',
  } satisfies CSSProperties,
  /** Form field label — Figma `I614:29682;242:4029` */
  formFieldLabel: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '19.2px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Enter Details totals — northstar `1:3748` */
  enterDetailsTotalCharges: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Summary links — northstar `1:3749` / `1:3750` */
  enterDetailsLink: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.textBody,
    textDecoration: 'underline',
    textDecorationStyle: 'solid',
    margin: 0,
    padding: 0,
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    whiteSpace: 'nowrap',
    textAlign: 'left',
  } satisfies CSSProperties,
  /** Payment heading — northstar `1:3755` */
  paymentSectionTitle: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 18,
    lineHeight: '22px',
    color: colors.textPrimary,
    margin: 0,
  } satisfies CSSProperties,
  /** Secure Checkout label — northstar `1:3760` */
  secureCheckoutCaption: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '16px',
    color: colors.textSecondary,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Legal block — northstar `1:3831` */
  enterDetailsLegal: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 13.5,
    lineHeight: '18.9px',
    color: '#5b5b6b',
    margin: 0,
  } satisfies CSSProperties,
  /** Rooms & Rates page title — Figma `18:7657` */
  roomsRatesTitle: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 24,
    lineHeight: '32px',
    color: colors.textPrimary,
    margin: 0,
    flex: 1,
    minWidth: 0,
  } satisfies CSSProperties,
  /** Disclaimer — Figma `18:7653` */
  roomsRatesDisclaimer: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 12,
    lineHeight: '14px',
    color: colors.textSecondary,
    margin: 0,
  } satisfies CSSProperties,
  roomsRatesDisclaimerLink: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 12,
    lineHeight: '14px',
    color: colors.textSecondary,
    textDecoration: 'underline',
    textDecorationStyle: 'solid',
    background: 'none',
    border: 'none',
    cursor: 'pointer',
    padding: 0,
    margin: 0,
    display: 'block',
    textAlign: 'left',
  } satisfies CSSProperties,
  /** Currency selector — Figma `18:7667` */
  currencySelector: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 12,
    lineHeight: '18px',
    color: '#666666',
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Inline trip summary — Figma `18:7669` */
  tripSummaryInline: {
    fontFamily: font,
    fontWeight: 400,
    fontSize: 16,
    lineHeight: '22px',
    color: colors.textBody,
    margin: 0,
  } satisfies CSSProperties,
  tripSummaryInlineBold: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 16,
    lineHeight: '22px',
    color: colors.textBody,
  } satisfies CSSProperties,
  /** Most popular tag — Figma `18:7679` */
  mostPopularTag: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: '#ffffff',
    margin: 0,
    textTransform: 'capitalize',
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** BEST VALUE tag — Figma `18:7709` */
  bestValueTag: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 12,
    lineHeight: '12px',
    color: colors.rateTagTealText,
    margin: 0,
    textTransform: 'uppercase',
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Customize and Reserve — Figma `18:7771` */
  customizeReserve: {
    fontFamily: font,
    fontWeight: 700,
    fontSize: 14,
    lineHeight: '18px',
    color: '#ffffff',
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
  /** Cancellation hint — Figma `18:7772` */
  cancellationHint: {
    fontFamily: font,
    fontWeight: 300,
    fontSize: 10,
    lineHeight: '14px',
    color: colors.textSecondary,
    margin: 0,
    textAlign: 'right',
    width: '100%',
  } satisfies CSSProperties,
  /** Filter pill active — Figma `18:7673` */
  filterPillActiveDark: {
    fontFamily: font,
    fontWeight: 600,
    fontSize: 14,
    lineHeight: '18px',
    color: colors.filterTealDark,
    margin: 0,
    whiteSpace: 'nowrap',
  } satisfies CSSProperties,
} as const;
